# Generated by Django 5.2.1 on 2025-05-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
        ('core_user', '0006_user_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post_liked',
            field=models.ManyToManyField(related_name='liked_by_user', to='core_post.post'),
        ),
    ]
